### ISSUE TITLE
Folder's not Carrying Over and Filename too long

### ISSUE THREAD

**Issue by Shellshock123** [DrWhoCares/imgdanke#89]
1. The first error is that the folders inside the Selected Folder do not carry over. The loose files inside the folders do.

2. The 2nd error is that im getting that the filename is too long. However, I've already done the Max Path variable thing.

**Comment by DrWhoCares** [comment]
So this has been partially fixed in 7a35f49e
Released in v1.2021.3.13

Things to note about this:
1. I still have no idea what's wrong with your filenames being too long. I need an example image to test.
2. Maintain Folder Structure is terrible to properly handle now. Basically, right now it'll work, but **only if** you don't have two files with the same name. This same issue is present with Include Subfolders, and you pick two files with the same name.

Closing for now. Open new, separate issues if issues persist.
